language: ruby

rvm:
  - 2.1.1
script:
  - bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: cTo7z40lt0TbzhRbqXBklWHGLeZSD0uL4Oiv7hQTknO453uEfpOGWk1vtkq6mkihIk1HNK6gimNSdAp/8SPvslysbBdB7HFRLZLe4UzSvq3dgZ67x2omYfATVSn9YtLBNYJ3e5Odlipcse1PTJhvz9tgtJ8w6ts0MOhGV6MMlF0=
  app: obscure-hollows-9519