language: ruby

rvm:
  - 2.1.1
script:
  - bundle exec rspec spec

deploy:
  provider: heroku
  api_key:
    secure: "jetUqJXFskwZxDRyZJPxk9SU4t2/B65KN//N4RXtrNiGvp78wzqZMonvW5dRFjA+5u4L/uYHQ6pA/oKT562sHo83fdANn7neHf8f3ItBmcYyPbSJE/mn+5xolVRaeSxE7XrwMEmQb955nPO5wak4wK7Xe/FGTqstsfrvqbNf/r4="
  app: sa-webdev-101614